/** UI chrome. Player strings are Swedish; admin strings stay English. */
export const strings = {
  appName: 'TiddeliQuiz',
  start: 'Starta',
  category: 'Kategori',
  topic: 'Ämne',
  questions: 'Antal frågor',
  difficulty: 'Svårighetsgrad',
  difficultyHard: 'Svår',
  difficultyMedium: 'Medel',
  difficultyEasy: 'Lätt',
  difficultyChildren: 'Barn',
  difficultyAll: 'Alla',
  showOptions: 'Visa alternativ',
  skip: 'Hoppa över',
  next: 'Nästa',
  summary: 'Sammanfattning',
  good: 'Rätt',
  bad: 'Fel',
  skipped: 'Hoppade över',
  adminTitle: 'Admin',
  username: 'Username',
  password: 'Password',
  login: 'Log in',
  logout: 'Log out',
  playerLogout: 'Logga ut',
  aiSection: 'AI backend',
  aiBaseUrl: 'Base URL',
  aiApiKey: 'API key',
  aiApiKeySet: 'A key is already stored. Paste a new one only if you want to replace it.',
  aiApiKeyMissing: 'No key stored yet. Paste it here, then save. It is never shown again.',
  aiModel: 'Model name',
  aiTimeout: 'Timeout (milliseconds)',
  aiTemperature: 'Temperature',
  aiThinking: 'Thinking mode',
  aiThinkingHint:
    'When on, the model reasons before writing questions. Slower and more expensive. Off is the default.',
  aiFetchSource: 'Read source pages',
  aiFetchSourceHint:
    'When on, the server downloads the subject source URL and sends the page text to the model. More tokens and slower. Works best with a normal web page. PDFs and login-walled books are not read. Off = the model is only told the link.',
  adminTabCategories: 'Categories',
  adminTabUsers: 'Users',
  adminTabSettings: 'Settings',
  adminTabAi: 'AI',
  adminTabLog: 'Log',
  categoriesSection: 'Categories',
  categoryName: 'Category name',
  categoryNameHint: 'Enter the name, then OK.',
  categoryNameRequired: 'Enter a category name.',
  ok: 'OK',
  categorySearch: 'Search categories',
  categoryCount: '{shown} of {total} categories',
  categoryEmpty: 'No categories match. Add one.',
  categorySubjects: '{count} subjects',
  addCategory: 'Add category',
  edit: 'Edit',
  editSubject: 'Edit subject',
  editSelected: 'Edit selected',
  rename: 'Rename',
  renameSubject: 'Rename subject',
  editPrompt: 'Edit prompt',
  remove: 'Remove',
  removeCategory: 'Remove category',
  removeCategoryWarnEmpty: 'Remove "{name}"? This cannot be undone.',
  removeCategoryWarn:
    'Remove "{name}"? This deletes {count} subjects and their questions. This cannot be undone.',
  adminBack: 'Back',
  topicsSection: 'Subjects',
  catalogSearch: 'Search subjects',
  catalogCount: '{shown} of {total} subjects',
  topicBankCount: '{count} questions',
  topicBankByDifficulty: '{label} {count}',
  catalogEmpty: 'No subjects in this category. Add one.',
  topicName: 'Subject',
  topicNameHint: 'Enter the name, then OK.',
  topicOptions: 'Number of options',
  topicPrompt: 'Prompt template',
  topicPromptHint:
    'Advanced. Filled from the name. Use {count}, {difficulty} and {optionCount}. Questions should be in Swedish.',
  topicSource: 'Source URL (optional)',
  topicSourceHint:
    'Link to a web page or online book. Questions will focus on that material. A PDF file is not read.',
  topicSourceFocus: 'How strictly to use the source',
  topicSourceFocusHint: 'Only = stay inside the source. Mainly = prefer it, fill gaps if needed.',
  topicSourceOnly: 'Only this source',
  topicSourceMainly: 'Mainly this source',
  topicSourceUsing: 'Source',
  addTopic: 'Add subject',
  removeTopic: 'Remove subject',
  removeTopicWarnEmpty: 'Remove "{name}"? This cannot be undone.',
  removeTopicWarn:
    'Remove "{name}"? This deletes its questions. This cannot be undone.',
  questionsSection: 'Questions',
  save: 'Save',
  cancel: 'Cancel',
  usersSection: 'Users',
  usersEmpty: 'No player accounts yet.',
  usersHint: 'Open a player to edit their private catalog. Categories stays platform-only.',
  usersOpenCatalog: 'Open catalog',
  myCategories: 'Mina kategorier',
  myEditOrCreate: 'Skapa / redigera',
  pickCategory: 'Välj kategori',
  myCategoriesHint:
    'Här skapar du egna ämnen och fyller din frågebank. Plattformens innehåll ändrar du inte här.',
  myCategoryEmpty: 'Inga egna kategorier ännu. Lägg till en.',
  myCatalogEmpty: 'Inga ämnen i den här kategorin. Lägg till ett.',
  myAddCategory: 'Lägg till kategori',
  myAddTopic: 'Lägg till ämne',
  myCategoryName: 'Kategorinamn',
  myCategoryNameHint: 'Skriv namnet, sedan OK.',
  myCategoryNameRequired: 'Ange ett kategorinamn.',
  myTopicName: 'Ämne',
  myTopicNameHint: 'Skriv namnet, sedan OK.',
  myTopicOptions: 'Antal alternativ',
  myTopicPrompt: 'Promptmall',
  myTopicPromptHint:
    'Avancerat. Fylls i från namnet. Använd {count}, {difficulty} och {optionCount}. Frågorna ska vara på svenska.',
  myTopicSource: 'Käll-länk (valfritt)',
  myTopicSourceHint:
    'Länk till en webbsida eller digital bok. Frågorna ska utgå från det materialet. En PDF-fil läses inte.',
  myTopicSourceFocus: 'Hur strikt källan ska användas',
  myTopicSourceFocusHint: 'Endast = stanna i källan. Främst = utgå från den, komplettera vid behov.',
  myTopicSourceOnly: 'Endast den här källan',
  myTopicSourceMainly: 'Främst den här källan',
  myTopicSourceUsing: 'Källa',
  myRemoveCategory: 'Ta bort kategori',
  myRemoveTopic: 'Ta bort ämne',
  myRemoveTopicWarnEmpty: 'Ta bort "{name}"? Det går inte att ångra.',
  myRemoveTopicWarn:
    'Ta bort "{name}"? Det tar bort ämnets frågor. Det går inte att ångra.',
  myRemoveCategoryWarnEmpty: 'Ta bort "{name}"? Det går inte att ångra.',
  myRemoveCategoryWarn:
    'Ta bort "{name}"? Det tar bort {count} ämnen och deras frågor. Det går inte att ångra.',
  myBackToPlay: 'Tillbaka till start',
  myEdit: 'Redigera',
  myRename: 'Byt namn',
  myRenameSubject: 'Byt namn på ämne',
  myRemove: 'Ta bort',
  myEditPrompt: 'Redigera prompt',
  mySelectAll: 'Markera alla',
  myDeleteSelected: 'Ta bort markerade',
  myDeleteAll: 'Ta bort alla',
  myRemoveQuestionsWarn: 'Ta bort {count} frågor? Det går inte att ångra.',
  myRemoveQuestionWarn: 'Ta bort den här frågan? Det går inte att ångra.',
  myRemovedQuestions: 'Tog bort {count} frågor.',
  myQuestionSearch: 'Sök frågor',
  myQuestionListCount: '{shown} av {total} frågor',
  myQuestionListEmpty: 'Inga frågor på den här nivån. Generera för att lägga till.',
  myQuestionCorrect: 'Rätt',
  mySave: 'Spara',
  mySaved: 'Sparat.',
  myCancel: 'Avbryt',
  myBankHint:
    'Generera lägger till frågor för den nivån. Generera valda fyller de ikryssade nivåerna i tur och ordning.',
  myBankGenerate: 'Generera',
  myBankGenerateAll: 'Generera valda',
  myBankGenerateAllTitle: 'Generera valda nivåer',
  myBankGenerateAllHint: 'Lägger till {count} frågor på varje vald nivå, en i taget.',
  myBankGenerateAllStart: 'Starta',
  myBankGenerateAllClose: 'Stäng',
  myBankGenerateAllWaiting: 'Väntar',
  myBankGenerateAllWorking: 'Arbetar…',
  myBankGenerateAllRowDone: 'Lade till {added}',
  myBankGenerateAllRowFailed: 'Misslyckades',
  myBankAddCount: 'Antal frågor att lägga till',
  myBankCount: '{count} i banken',
  myBankAdded: 'Lade till {added} frågor.',
  myBankAddedSome: 'Lade till {added} frågor. Hoppade över {skipped} dubbletter.',
  myCategoryCount: '{shown} av {total} kategorier',
  myCatalogCount: '{shown} av {total} ämnen',
  myCategorySubjects: '{count} ämnen',
  myTopicBankCount: '{count} frågor',
  myPlayEmptyHint: 'Inga egna ämnen att spela ännu. Använd Skapa / redigera för att lägga till frågor.',
  settingsSection: 'Settings',
  settingsAiHint: 'Model, API key, thinking, and whether to download source pages.',
  settingsLogHint: 'Debug log and log level.',
  saveAi: 'Save AI settings',
  bankSection: 'Platform bank',
  bankHint:
    'Generate adds questions for that level. Generate selected fills the ticked difficulties with the same batch size.',
  bankCount: '{count} in bank',
  bankGenerate: 'Generate',
  bankGenerateAll: 'Generate selected',
  bankGenerateAllTitle: 'Generate selected difficulties',
  bankGenerateAllHint: 'Adds {count} questions to each selected level, one after another.',
  bankGenerateAllStart: 'Start',
  bankGenerateAllClose: 'Close',
  bankAddCount: 'Questions to add',
  bankGenerating: 'Generating questions…',
  bankGeneratingAll: 'Generating {difficulty} ({current} of {total})…',
  bankGenerateAllDone: 'Done',
  bankGenerateAllWaiting: 'Waiting',
  bankGenerateAllWorking: 'Working…',
  bankGenerateAllRowDone: 'Added {added}',
  bankGenerateAllRowFailed: 'Failed',
  bankGenerateFailed: 'Could not generate questions. Check AI settings and try again.',
  bankAdded: 'Added {added} questions.',
  bankAddedSome: 'Added {added} questions. Skipped {skipped} duplicates.',
  bankGenerateAllFailed: 'Could not generate: {failed}.',
  questionSearch: 'Search questions',
  questionListCount: '{shown} of {total} questions',
  questionListEmpty: 'No questions at this difficulty. Generate to add some.',
  questionText: 'Question',
  questionOption: 'Option {n}',
  questionCorrect: 'Correct',
  questionExplanation: 'Explanation',
  questionSource: 'Wikipedia article (optional)',
  addOption: 'Add option',
  removeOption: 'Remove option',
  removeQuestion: 'Remove question',
  removeQuestionWarn: 'Remove this question? This cannot be undone.',
  selectAll: 'Select all',
  deleteSelected: 'Delete selected',
  deleteAll: 'Delete all',
  clearQuestions: 'Clear all questions',
  clearQuestionsWarn:
    'Remove all {count} questions in "{name}"? This cannot be undone.',
  clearDifficultyWarn:
    'Remove all {count} {difficulty} questions in "{name}"? This cannot be undone.',
  myClearDifficultyWarn:
    'Ta bort alla {count} {difficulty}-frågor i "{name}"? Det går inte att ångra.',
  removeQuestionsWarn: 'Remove {count} questions? This cannot be undone.',
  removedQuestions: 'Removed {count} questions.',
  questionInvalid: 'Enter the question, at least two options, and mark the correct one.',
  questionDuplicate: 'A question with this text already exists at this difficulty.',
  logSection: 'Debug log',
  logLevel: 'Log level',
  logLevelHint:
    'The log below shows this level and more serious ones. Debug includes full AI prompts and replies. The API key is never logged.',
  logLevelError: 'Error',
  logLevelWarn: 'Warning',
  logLevelInfo: 'Info',
  logLevelDebug: 'Debug',
  saveLogLevel: 'Save log level',
  saved: 'Saved.',
  loginFailed: 'Wrong username or password.',
  loadFailed: 'Could not load admin data.',
  generating: 'Skapar frågor…',
  generatingHint2: 'Skriver svar och förklaringar…',
  generatingHint3: 'Fortfarande igång, det kan ta en liten stund…',
  generatingWait:
    'Vanlig väntetid: ungefär {seconds} sekunder för {count} frågor med {options} alternativ vardera.',
  generatingElapsed: '{seconds}s har gått',
  generateFailed: 'Kunde inte skapa frågor. Försök igen.',
  startFailed: 'Kunde inte starta quizen. Försök igen.',
  bankTooSmall:
    'Det finns bara {available} frågor för det här ämnet och den här svårigheten. Välj färre frågor eller ett annat ämne.',
  moreQuestions: 'Fler frågor',
  moreQuestionsNone: 'Inga nya frågor kvar för det här ämnet och den här svårigheten.',
  replayBank: 'Börja om från början',
  replayBankHint: 'Du har gjort alla frågor i den här banken. Du kan börja om.',
  roundShort: 'Bara {count} nya frågor fanns (du ville ha {requested}).',
  bankAvailable: '{count} frågor i banken för det här ämnet och den här svårigheten.',
  roundMissing: 'Ingen quiz är laddad. Starta en ny omgång från startsidan.',
  choosePath: 'Hur vill du fortsätta?',
  chooseAdmin: 'Admin',
  chooseUser: 'Logga in',
  chooseGuest: 'Fortsätt utan att logga in',
  userLoginTitle: 'Logga in',
  playerUsername: 'Användarnamn',
  playerPassword: 'Lösenord',
  playerLoginFailed: 'Fel användarnamn eller lösenord.',
  backToChoose: 'Tillbaka',
  loggedInAs: 'Inloggad som {name}',
  playingAsGuest: 'Gäst',
  continue: 'Fortsätt',
  back: 'Tillbaka',
  retryAll: 'Försök igen (alla)',
  retryFailed: 'Försök igen (fel)',
  quit: 'Avsluta',
  downloadCopy: 'Ladda ner kopia',
  downloadStudent: 'För elever',
  downloadTeacher: 'För lärare',
  questionOf: 'Fråga',
  sourceLink: 'Läs mer',
  loadingCatalog: 'Laddar…',
  noCategories: 'Inga kategorier att spela ännu.',
  noTopics: 'Inga ämnen att spela ännu.',
  noTopicsInCategory: 'Inga ämnen i den här kategorin.',
  catalogLoadFailed: 'Kunde inte ladda kategorier.',
  adPlaceholder: 'Annons',
  myResults: 'Resultat',
  myResultsEmpty: 'Inga avslutade quiz ännu.',
  myResultsCount: '{count} quiz',
  myResultsTotals: '{good} rätt · {bad} fel · {skipped} hoppade över',
  myResultsScore: '{good}/{count} rätt ({percent}%)',
  myPlayAgain: 'Spela igen',
  myResultsSaveFailed: 'Kunde inte spara resultatet.',
  myPlayAgainGone: 'Det ämnet finns inte längre.',
}
